spring.application.name=queue-service
server.port=8082

# MySQL — queue's OWN database
spring.datasource.url=jdbc:mysql://localhost:3306/hospital_queue?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=B1sm1lla#
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Clean up: Hibernate detects this automatically now
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Data Initialization Fix
spring.sql.init.mode=always

# Logging
logging.config=classpath:log4j2.xml
