spring.application.name=monitor-service
server.port=8084

# MongoDB Configuration
spring.mongodb.uri=mongodb://localhost:27017/hospital_monitor

# Logging
logging.config=classpath:log4j2.xml
services.queue.url=http://localhost:8082
services.doctor.url=http://localhost:8083